language: node_js
node_js:
- '0.10'
before_script:
- gem install travis-artifacts
- bower install
env:
  global:
  - ARTIFACTS_AWS_REGION=eu-west-1
  - ARTIFACTS_S3_BUCKET=atlantisjs
  - secure: EyQ+4g03UKWmWZCjWsVpsj1FgYI8YN2ocRBzAwAkgPhN0BAx8BrOvlbKVyHWN/jArNmP/RyTXDeNEb5H/nszgiwptV1K4R3Cvl2Rwy73OUiYMlI5P3BbCdiDcJXwl7YakmO3g+5UEaRjVcXaLq3/awc9h5gdgRA5CrS/CVO/LeM=
  - GH_OWNER: Axonn
  - GH_PROJECT_NAME: Atlantis.js
  - secure: BaYLkWTAIfQC4agxluY+P0CWb8H0kiNLFPm4b1xkqdqo4FT0faQQDhbKidrU8sUYDfGjNmEJXN0vvQcQKFP5iiRsegaoApWIwhLafleEg0eqj4555kaWDtNqvEM8pXez/hFIFTA68PhXjyG7PzNSs+GTlyp9YaTy6iu7/3xzztE=
  - secure: JbBXuZ/FQ5WfHvdTK/7dckl6LQtvjlPOarz1BdoD7H5pCXkOxuqbdWkI79FskJiufI1d0/7zw0NAGvveJIlE8lDC3l5zBl7652cohqBbU3X4LDhWEE01DRf0CihtbGYYSqsyDaEjoDns86hIi6vTIRHwL0LtpzB9VizDIanNR+k=
  - secure: TkBHkxGu0uhJr9Y5gtD/1DL8jGKF8aOHgVLmjN/4SiqvwcYviQGUb/ew9DLIctu5J9xr3mMFePdEXSrJiOoqtt2owqbtYXuVH88Gnh9sY/Q4pqyo4UqE4E2BYiZnRLORRUi61uUJx3nis6kz/r9N+se7mfRIk0HZwLYrqlyOp5U=
after_success:
- version=$(head -n 1 version.txt)
- oldversion=$(git describe --abbrev=0 --tags)
- if [ "$version" != "$oldversion" ]; then
- if git checkout master; then git checkout -b master; fi
- git config user.name "travis-ci"
- git config user.email "corwin.tomkinson@adfero.co.uk"
- cp build/js/gzip/atlantis.js atlantis.js
- cp build/js/gzip/atlantisjs.css atlantisjs.css
- git add -f atlantis.js
- git add -f atlantisjs.css
- git commit -am "add build files to master [ci skip]"
- travis-artifacts upload --path atlantis.js --target-path atlantisjs/$version
- travis-artifacts upload --path atlantisjs.css --target-path atlantisjs/$version
- travis-artifacts upload --path build/js/fonts --target-path atlantisjs/$version/fonts
- echo $version
- git tag -a $version -m "new AtlantisJS Version released"
- newversion=$(git describe --abbrev=0 --tags)
- echo $newversion
- git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:master
  --tags > /dev/null 2>&1
- fi
